<?php

/**
 * @file
 *
 */

include_once 'ding_nyhedslisten.features.inc';

/**
 * Implements hook_menu().
 */
function ding_nyhedslisten_menu() {
  $items = array();

  $items['admin/config/ding/newslists'] = array(
    'title' => 'News lists',
    'description' => 'Configure news lists',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_nyhedslisten_admin_settings_form'),
    'access arguments' => array('administer content'),
    'file' => 'includes/ding_nyhedslisten.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * ctools_plugin_example/panels are used.
 */
function ding_nyhedslisten_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}
